#!/usr/bin/env bash
#
# Local app -> glyph overrides.
#
# icon_map.sh is generated by the sketchybar-app-font project and is replaced
# wholesale on every font update, so edits to it do not survive. This file is
# applied after it and is yours to extend.
#
# Use it for apps the upstream map does not know (they render as :default:) or
# where you want a different glyph than the one shipped.
#
# To find the available glyph names:
#   grep -o ':[a-z0-9_]*:' ~/.config/sketchybar/icon_map.sh | sort -u
#
# $1 is the application name exactly as yabai reports it:
#   yabai -m query --windows | jq -r '.[].app' | sort -u

__icon_map_local() {
  case "$1" in
    # "ego lite" is a Chromium-based browser the upstream map does not know.
    "ego lite")
      icon_result=":google_chrome:"
      ;;
    *)
      # No override: leave whatever icon_map.sh decided.
      return 1
      ;;
  esac
  return 0
}
