#!/bin/sh
#
# Toggle the desktop background between ayu dark and true OLED black.
#
# Affects sketchybar's pills and Ghostty's terminal background together, so the
# bar and the windows under it stay the same colour in either mode.
#
#   ayu     #0b0e14  the palette's background, matching Neovim
#   black   #000000  pixels fully off on an OLED panel
#
# Usage:  theme_toggle.sh [ayu|black|toggle]   (default: toggle)
#
# --- Why each side is done the way it is -----------------------------------
#
# sketchybar reads its colour from a generated override file that colors.sh
# sources, then reloads. Simple, because sketchybar re-executes its whole
# config on reload.
#
# Ghostty gets the change twice, on purpose:
#
#   1. A config include file, so the choice survives a restart. Ghostty has no
#      CLI reload action -- reload is a keybind (super+shift+,) -- so writing
#      the file alone would not affect running windows.
#   2. An OSC 11 escape sequence written straight to each Ghostty tty, which
#      changes the background of running windows instantly with no permissions
#      and no simulated keypresses.
#
# Together: instant effect now, correct colour after the next restart.
#
# --- Colour management ------------------------------------------------------
#
# Ghostty colour-manages its output; sketchybar writes raw framebuffer values.
# On the P3 built-in display sRGB #0b0e14 renders as #0c0e13, so the bar has to
# use that corrected literal to match -- see colors.sh for the full reasoning.
#
# Black needs no correction: #000000 is a fixed point of the conversion. That is
# why the two modes below are not symmetrical.

set -eu

SKETCHYBAR_DIR="$HOME/.config/sketchybar"
OVERRIDE="$SKETCHYBAR_DIR/.theme_override.sh"
GHOSTTY_DIR="$HOME/Library/Application Support/com.mitchellh.ghostty"
GHOSTTY_INC="$GHOSTTY_DIR/theme-background"

SB=/opt/homebrew/bin/sketchybar

# ayu background: what Ghostty is told, and what the bar must paint to match it
# after Ghostty's colour conversion.
AYU_GHOSTTY=0b0e14
AYU_BAR=0xff0c0e13

BLACK_GHOSTTY=000000
BLACK_BAR=0xff000000

# --- Work out the target mode ----------------------------------------------

current() {
  if [ -f "$OVERRIDE" ] && grep -q 'THEME_MODE=black' "$OVERRIDE" 2>/dev/null; then
    echo black
  else
    echo ayu
  fi
}

MODE="${1:-toggle}"
if [ "$MODE" = "toggle" ]; then
  if [ "$(current)" = "black" ]; then MODE=ayu; else MODE=black; fi
fi

case "$MODE" in
  ayu)   BAR_BG=$AYU_BAR;   GHOSTTY_BG=$AYU_GHOSTTY ;;
  black) BAR_BG=$BLACK_BAR; GHOSTTY_BG=$BLACK_GHOSTTY ;;
  *) echo "usage: $(basename "$0") [ayu|black|toggle]" >&2; exit 2 ;;
esac

# --- sketchybar -------------------------------------------------------------

cat > "$OVERRIDE" <<EOF
# Generated by theme_toggle.sh -- do not edit by hand.
# Sourced at the end of colors.sh to override the island background.
THEME_MODE=$MODE
export ISLAND_BG=$BAR_BG
EOF

# --- Ghostty: persistent half ----------------------------------------------

mkdir -p "$GHOSTTY_DIR"
cat > "$GHOSTTY_INC" <<EOF
# Generated by theme_toggle.sh -- do not edit by hand.
# Included from the main Ghostty config via config-file.
background = $GHOSTTY_BG
EOF

# --- Ghostty: instant half --------------------------------------------------
#
# OSC 11 sets the background of a live terminal. It has to be written to the
# tty of each Ghostty surface; tmux clients expose theirs via list-clients,
# and any non-tmux shell is found by walking the process tree up to ghostty.
#
# Writing to a tty can fail (a closed window, a tty that has gone away), which
# must not abort the rest of the toggle -- hence the guards.

osc11() {
  tty_path="$1"
  [ -w "$tty_path" ] || return 0
  printf '\033]11;#%s\007' "$GHOSTTY_BG" > "$tty_path" 2>/dev/null || true
}

# tmux clients: their client_tty IS the Ghostty surface.
if command -v tmux >/dev/null 2>&1; then
  tmux list-clients -F '#{client_tty}' 2>/dev/null | while IFS= read -r t; do
    [ -n "$t" ] && osc11 "$t"
  done
fi

# Plain (non-tmux) Ghostty shells: find ttys whose process ancestry reaches
# ghostty. Skips ttys already handled above; writing twice would be harmless
# anyway, but this keeps the work proportional to the number of windows.
for t in $(ps -eo tty= 2>/dev/null | sort -u | grep '^ttys' || true); do
  dev="/dev/$t"
  [ -w "$dev" ] || continue
  pid=$(ps -t "$t" -o pid= 2>/dev/null | head -1 | tr -d ' ')
  [ -z "$pid" ] && continue
  cur="$pid"
  i=0
  while [ "$i" -lt 8 ]; do
    ppid=$(ps -o ppid= -p "$cur" 2>/dev/null | tr -d ' ' || true)
    if [ -z "$ppid" ] || [ "$ppid" = "0" ] || [ "$ppid" = "1" ]; then
      break
    fi
    case "$(ps -o comm= -p "$ppid" 2>/dev/null || true)" in
      *ghostty*) osc11 "$dev"; break ;;
    esac
    cur="$ppid"
    i=$((i + 1))
  done
done

# --- Apply to sketchybar ----------------------------------------------------

"$SB" --reload >/dev/null 2>&1 || true

echo "$MODE"
